theme: jekyll-theme-slate
logo: assets/Pantala_logo_v3.png
title: William R. Kuhn
description: Entomologist, evolutionary biologist, biodiversity informaticist
show_downloads: False
google_analytics: UA-121992442-1
